[#112] segfault on too many metrics
pgexporter/pgexporter pull request #114
Opened 2023-10-15 05:27 UTC by resyfer

2023-10-15 11:58 UTC, jesperpedersen requested changes

2023-10-15 11:58 UTC, jesperpedersen commented on src/libpgexporter/yaml_configuration.c
> +      prometheus_t* prom = &prometheus[prometheus_idx + i];
Start with `NULL`, and assign after the check below

2023-10-15 13:50 UTC, resyfer commented
PTAL

2023-10-15 14:35 UTC, jesperpedersen requested changes

2023-10-15 14:35 UTC, jesperpedersen commented on src/libpgexporter/yaml_configuration.c
> +      prom = &prometheus[prometheus_idx + i];
Same issue - move it past the check

2023-10-15 14:45 UTC, resyfer commented on src/libpgexporter/yaml_configuration.c
> +      prom = &prometheus[prometheus_idx + i];
oh okay, my bad, I got it.

2023-10-15 15:12 UTC, merged

2023-10-15 15:13 UTC, jesperpedersen commented
Merged, and back-ported.

Thanks for your contribution !

2023-10-17 17:53 UTC, resyfer commented
Thanks for the review!