[#34] Implement metric collectors for pgexporter
pgexporter/pgexporter pull request #61
Opened 2023-04-22 20:18 UTC by resyfer

Fixes the issue #34

2023-04-24 11:16 UTC, jesperpedersen requested changes

2023-04-24 11:16 UTC, jesperpedersen commented on doc/GETTING_STARTED.md
> +      --no-collectors NAME_1,NAME_2,...,NAME_N  List of collectorss that will be disabled
No

2023-04-24 11:16 UTC, jesperpedersen commented on doc/GETTING_STARTED.md
> +      --no-collectors-defaults                  Disable all the default collectors
No

2023-04-25 06:31 UTC, jesperpedersen commented
@resyfer When you think you are done send me a "PTAL"

2023-04-25 06:51 UTC, resyfer commented
@jesperpedersen I feel I am done. PTAL

2023-04-25 07:35 UTC, merged

2023-04-25 07:36 UTC, jesperpedersen commented
Merged.

Thanks for your contribution !