[#32] Improve built-in /metrics endpoints to use both counter and gauge
pgexporter/pgexporter pull request #62
Opened 2023-04-25 15:53 UTC by resyfer

@jesperpedersen This is the implementation of what I had in my mind for #32. I still haven't added an install instruction for `internal.yml` file to have the path `/etc/pgexporter/internal.yml`, but using the following command before running the binary should do it.

```sh
sudo cp ./contrib/yaml/internal.yml /etc/pgexporter/internal.yml
```

I am not much familiar with writing CMake files or Spec files for RPM, so I'll look into those for this when this idea gets a green signal.

PS: This is just a bare-bones working change to the repo to demonstrate my idea. This needs work here and there, which I'll be glad to do.

2023-04-26 06:22 UTC, jesperpedersen commented
Ok, I get where you are coming from.

However, `internal.yml` def lives in `src/yaml` instead, and you can't assume it should loaded from `/etc/pgexporter` as the configuration can be overwritten by `-c`.

Start by investigation if it can be embedded into the shared library, and loaded from there. Or do it as an `internal.h` with the text string.

Latter is likely more acceptable...

As is, no

2023-04-26 15:13 UTC, jesperpedersen commented
Much happier with that - go ahead

2023-04-26 17:45 UTC, resyfer commented
@jesperpedersen PTAL

2023-04-27 03:35 UTC, resyfer commented
I have yet to identify the metrics that are better represented by counter than a gauge and I'll start looking into it.

2023-04-27 06:38 UTC, jesperpedersen requested changes

2023-04-27 06:38 UTC, jesperpedersen commented on src/include/internal.h
> +#ifndef PGEXPORTER_INTERNAL_H
Remember header

2023-04-27 06:38 UTC, jesperpedersen commented on src/include/pgexporter.h
> +#define MAX_PATH              1024
If you are doing this then right-align

2023-04-27 06:38 UTC, jesperpedersen commented on src/include/pgexporter.h
> +#define SORT_DATA 1
Lets keep the `SORT_DATA0` name - we may want to sort by multiple data columns in the future

2023-04-27 06:38 UTC, jesperpedersen commented on src/libpgexporter/yaml_configuration.c
> +      printf("Hi\n");
Hello !

2023-04-27 06:38 UTC, jesperpedersen commented on src/main.c
> +#include <pgexporter.h>
This one is always first

2023-04-27 06:38 UTC, jesperpedersen commented on src/main.c
> +#include <stdbool.h>
System include

2023-04-27 06:38 UTC, jesperpedersen commented
Sounds good - I gave the patch a quick scan...

2023-04-27 17:38 UTC, resyfer commented
@jesperpedersen I've made the requested changes, and I'll give a PTAL after finishing looking into which metrics need to be collectors

2023-05-03 14:28 UTC, merged

2023-05-03 14:28 UTC, jesperpedersen commented
Merged.

Thanks for your contribution !

2023-05-03 18:12 UTC, resyfer commented
@jesperpedersen Thank you for the review and thank you for the (very long) discussion around it! I hope this solves the problem that the issue aimed to point out.